<?php

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

// Según el enunciado, considero a los dos primeros elementos como 1 y 2

function r_fibonacci($f) {
	if ($f < 1) {
		throw new Exception("No pibe");
	} else if ($f == 1) { 
		return 1;
	} else if ($f == 2) {
		return 2;
	} else {
		return r_fibonacci($f - 1) + r_fibonacci($f - 2);
	}
}

function fibonacci($f) {
	$f++; // Incremento en uno para que el primer elemento sea 1 y el segundo sea 2
	return round((pow(((1 + sqrt(5)) / 2), $f) - pow((-1 / (1 + sqrt(5)) / 2), $f)) / sqrt(5));
}

//for ($i = 1; $i <= 10; $i++) {
//	echo round(fibonacci($i)) . "\n";
//}

$i = 1;
$f = 0;
$sum = 0;
$f = fibonacci($i);

while($f <= 4000000){
	if ($f % 2 == 0) {
		$sum += $f;
	}
	$i++;
	$f = fibonacci($i);
}

echo $sum . "\n";
